#pragma once

// Discrete LED nets from KiCad: LED1..LED7 = B1..B7.

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define VIA_EEPROM_CUSTOM_CONFIG_SIZE 32
#define EECONFIG_KB_DATA_SIZE VIA_EEPROM_CUSTOM_CONFIG_SIZE
#define VIA_FIRMWARE_VERSION 0x00000001

#define USB_POLLING_INTERVAL_MS 1
